# consuming-repo/.github/workflows/trigger-shared-workflow.yml
name: Trigger Shared Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  call-shared-workflow:
    uses: tejademo-scs/shared-repo/.github/workflows/shared-workflow.yaml  # Reference shared repo workflow
    with:
      run-tests: true
