name: Aqua
on:
  push:
    branches:
      - main
  workflow_dispatch:   
jobs:
  aqua:
    name: Aqua scanner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --debug --sast --reachability --scanners misconfig,vuln,secret --package-json --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
env:
    AQUA_KEY: ${{ secrets.AQUA_KEY }}
    AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
    TRIVY_RUN_AS_PLUGIN: 'aqua'
    ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
    TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
    TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }} 
