name: Build & Test
 
on: [pull_request, push]
 
jobs:
  scan:
    name: Code Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --sast --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable reachability scanning, add: --reachability
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }} 
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    needs: scan
    steps:
      - uses: actions/checkout@v3
 

 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
 
      - name: Run DVGA
        run: |
          nohup python3 ./app.py &
      - name: Wait for server (sleep 5 secs)
        run: |
          sleep 180
      - name: Run DVGA Tests
        run: |
          python3 -m pytest tests/*
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
      # Added for SBOM generation
      - name: Build Docker Image
        run: docker build -t knightfortheright/mytest:v4 .
      - name: Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.codesec.aquasec.com
          export TRIVY_USERNAME=teja.chittamuri@aquasec.com
          export TRIVY_PASSWORD=Jesus@saves2001
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://api.cloudsploit.com \
            --artifact-path knightfortheright/mytest:v3 \
            --db-repository="registry.aquasec.com/trivy-db:2" \
            --tiryv-java-db-repository="registry.aquasec.com/trivy-java-db:1" \
            --trivy-checks-bundle-repository="registry.aquasec.com/trivy-checks:1" \
            --quiet \
            --output billy.log
